name: Build TelemetryStealer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build solution
      run: msbuild TelemetryStealer.sln /p:Configuration=Release

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: TelemetryStealer-Release
        path: TelemetryStealer\bin\Release\
